FROM crisbal/torch-rnn:base
MAINTAINER InnovativeInventor

# Copying files
COPY trump_tweets.h5 /root/torch-rnn/data/trump_tweets.h5
COPY trump_tweets.json /root/torch-rnn/data/trump_tweets.json
COPY trump_speeches.h5 /root/torch-rnn/data/trump_speeches.h5
COPY trump_speeches.json /root/torch-rnn/data/trump_speeches.json

WORKDIR /root/torch-rnn
